name: Continuous Integration
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint codebase
        run: yarn lint:eslint:fix

      - name: Test codebase
        run: yarn test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          # token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          directory: coverage
          fail_ci_if_error: true

      - name: Build Project
        run: yarn build

      # commenting for now to make CI green , will try this 
      # - name: run Lighthouse CI
      #   run: |
      #     yarn global add @lhci/cli@0.8.x
      #     lhci autorun --collect.staticDistDir

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
